spring.application.name=DACK_QuanLyNhaTro

spring.datasource.url=jdbc:mysql://localhost:3306/quanlynhatro
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

